apiVersion: v1
kind: Service
metadata:
    name: "samplemicroservicescluster-2aea"
    labels:
        app: "samplemicroservicescluster-2aea"
spec:
    type: LoadBalancer
    ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "samplemicroservicescluster-2aea"
