apiVersion: v1
kind: Service
metadata:
    name: "samplemicroservicescluster-2aea"
    labels:
        app: "samplemicroservicescluster-2aea"
spec:
    type: NodePort
    ports:
    - nodePort: 32410
      port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "samplemicroservicescluster-2aea"
