apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-api
  name: basket-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
    name: http
  selector:
    io.kompose.service: basket-api
