apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-db
  name: basket-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basket-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: basket-db
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: ""
        name: shoppingredis
        ports:
        - containerPort: 6379
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-data
        - mountPath: /usr/local/etc/redis/redis.conf
          name: redis-conf-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
      - name: redis-conf-data
        persistentVolumeClaim:
          claimName: redis-conf-data
status: {}
