apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-api
  name: basket-api
spec:
  ports:
  - name: "6001"
    port: 6001
    targetPort: 80
  selector:
    io.kompose.service: basket-api
status:
  loadBalancer: {}
