on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: samplecontreg20062021.azurecr.io
        username: ${{ secrets.acr_samplecontreg20062021_username }}
        password: ${{ secrets.acr_samplecontreg20062021_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/MicroserviceSample/src" -f  "MicroserviceSample/src/Services/Basket/Basket.API/Dockerfile" -t samplecontreg20062021.azurecr.io/samplemicroservicescluster:${{ github.sha }} --label dockerfile-path=MicroserviceSample/src/Services/Basket/Basket.API/Dockerfile
        docker push samplecontreg20062021.azurecr.io/samplemicroservicescluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_samplemicroservicescluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep samplemicroservicesclusterad62 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace samplemicroservicesclusterad62`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: samplemicroservicesclusterad62
        container-registry-url: samplecontreg20062021.azurecr.io
        container-registry-username: ${{ secrets.acr_samplecontreg20062021_username }}
        container-registry-password: ${{ secrets.acr_samplecontreg20062021_password }}
        secret-name: samplemicrosdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: samplemicroservicesclusterad62
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          samplecontreg20062021.azurecr.io/samplemicroservicescluster:${{ github.sha }}
        imagepullsecrets: |
          samplemicrosdockerauth
